"use client";

import Head from "next/head";
import Script from "next/script";
import style from "@/components/privacy.module.scss";
import Header from "@/components/header";
import Footer from "@/components/Footer";

export default function PrivacyPolicy() {
  return (
    <>
      <Head>
        <title>UX GROUP - Políticas de privacidade</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <!-- Hotjar Tracking Code for https://uxgroup.com.br/ --> */}

      <Script>
          {` (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:5174280,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');');
  `}</Script>


      {/* <!-- Google Tag Manager --> */}
      <Script>{`(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                    })(window,document,'script','dataLayer','GTM-5M78MWM');`}</Script>
      {/* <!-- End Google Tag Manager --> */}
      {/* <!-- Google Tag Manager (noscript) --> */}
      <noscript>
        <iframe
          src="https://www.googletagmanager.com/ns.html?id=GTM-5M78MWM"
          height="0"
          width="0"
          style={{ display: "none", visibility: "hidden" }}
        ></iframe>
      </noscript>
      {/* <!-- End Google Tag Manager (noscript) --> */}
      <Header />
      <section className={` text-black ${style.container}`}>
        <div className={style.margin}>
          <div className={style.titleBlock}>
            <h1 className={style.title}>POLÍTICA DE PRIVACIDADE UX GROUP</h1>
          </div>
          <div className={style.content}>
            <div className={style.description}>
              <p>
                Esta Política de Privacidade de Dados Pessoais da
                <span style={{ fontWeight: "bold" }}> UX HOLDING LTDA </span>
                (“UX GROUP”) faz parte integrante deste Site. Esta Política tem
                como finalidade a demonstrar o compromisso da
                <span style={{ fontWeight: "bold" }}> UX GROUP </span> com o
                tratamento, segurança e a privacidade dos dados pessoais
                coletados dos usuários (Usuários) , em razão do acesso e uso
                deste Site, funcionalidades, recursos e serviços (Plataforma).
              </p>
              <p>
                Nossa política de privacidade tem como objetivo explicar aos
                usuários como seus dados e informações são tratados, armazenados
                e utilizados em nossa plataforma. As informações dos usuários
                não serão fornecidas, publicadas ou comercializadas em quaisquer
                circunstâncias, exceto conforme previsto nesta Política de
                Privacidade.
              </p>
              <p>
                Ainda, esta Política complementa os Termos e Condições da
                plataforma e quaisquer outros termos aplicáveis aos serviços da
                UX GROUP. Os termos e condições desta Política poderão ser
                atualizados, de tempos em tempos.
              </p>
              <p>
                Os dados pessoais dos Usuários serão tratados, utilizados,
                armazenados e protegidos de acordo com o disposto nesta Política
                e na legislação aplicável.
              </p>
              <p>
                A UX GROUP utiliza e adota processos, técnicas, mecanismos e
                procedimentos de segurança e prevenção adequados e apropriados
                para assegurar a devida proteção, incluindo em sua transmissão,
                por meio de ferramentas de criptografia, contra eventuais
                incidentes de segurança, ocorrências ou suspeitas de acessos,
                utilizações, alterações, apropriação e destruição não-autorizada
                por terceiros, passível de comprometer ou ameaçar a integridade,
                confidencialidade, autenticidade e disponibilidade dos dados
                pessoais dos Usuários e demais informações.
              </p>
              <p>
                Todas e quaisquer dúvidas e esclarecimentos sobre a coleta e
                tratamento de dados pessoais ou o disposto neste Política, por
                favor, entre em contato conosco pelo seguinte e-mail:
                <span style={{ fontWeight: "700" }}>
                  marketing@uxgroup.com.br
                </span>
              </p>
              <p>
                O uso continuado de nosso site será considerado como aceitação
                de nossas práticas em torno de privacidade e informações
                pessoais. Se você tiver alguma dúvida sobre como lidamos com
                dados do usuário e informações pessoais, entre em contacto
                connosco.
              </p>
              <h2 style={{ paddingBottom: "10px" }}>
                1. COLETA DOS SEUS DADOS PESSOAIS <br></br>
                <span style={{ marginLeft: "10px" }}>
                  <span style={{ fontWeight: "700" }}>1.</span> Identidade e
                  informações de contato do Controlador dos Dados Pessoais dos
                  Usuários. 1 UX HOLDING LTDA. AV. PIRAIBA, 159, CENTRO
                  COMERCIAL JUBRAN, BARUERI/SP, CEP 06.460-121. inscrita no
                  Cadastro Nacional de Pessoas Jurídicas do Ministério da
                  Fazenda (CNPJ/MF) sob n. 32.926.520/0001-16, doravante
                  denominada UX GROUP.
                </span>
              </h2>
              <h2>2. INFORMAÇÕES FORNECIDAS PELO USUÁRIO </h2>
              <span style={{ paddingLeft: "10px" }}>
                Informações solicitadas. Para acessar, utilizar e otimizar a sua
                experiência na Plataforma da UX GROUP, podemos solicitar o
                fornecimento de determinados dados pessoais. Ou seja,
                informações que possam ser usadas para identificá-lo
                pessoalmente ou contatá-lo, como seu nome, endereço de e-mail,
                número de telefone, endereço residencial, nome de usuário e/ou
                URL do perfil em redes sociais. ação, cópia, uso ou modificação
                não autorizadas. 1° Coleta de informações pessoais. Para o
                melhor uso da Plataforma, o usuário poderá fornecer, entre
                outros, os seguintes dados para assegurar a melhor experiência e
                execução dos serviços disponibilizados na Plataforma:
              </span>
              <br></br>
              <span style={{ paddingLeft: "10px" }}>
                <span style={{ fontWeight: "700" }}>1.</span> Dados de
                Identificação. Nome, endereço, endereço de e-mail, número de
                telefone, profissão, data de nascimento, idioma, número de
                documento de identidade e número de inscrição no Cadastro de
                Pessoa Física.
              </span>
              <br></br>
              <span style={{ paddingLeft: "10px" }}>
                <span style={{ fontWeight: "700" }}>2.</span> Outros Dados de
                Identificação. Outros documentos pessoais, dados de contato
                (e-mail, endereço, telefone, identificadores de aplicativos de
                comunicação e redes sociais), dados profissionais.{" "}
              </span>
              <br></br>
              <span style={{ paddingLeft: "10px" }}>
                <span style={{ fontWeight: "700" }}>3.</span> Dados financeiros
                e informações patrimoniais. Modo de pagamento usado, data e
                hora, valor do pagamento, data de vencimento do outros detalhes
                referentes à transação (incluindo histórico de transações).
              </span>
              <br></br>
              <span style={{ paddingLeft: "10px" }}>
                <span style={{ fontWeight: "700" }}>4.</span> Informações de
                uso. Informações de páginas e conteúdos referentes ao que você
                visualiza, buscas por Anúncios, reservas que você fez e outras
                ações na Plataforma UX GROUP.{" "}
              </span>
              <br></br>
              <span style={{ paddingLeft: "10px" }}>
                <span style={{ fontWeight: "700" }}>5.</span> Informações
                coletadas automaticamente pelo uso da plataforma. Após a
                instalação da plataforma, algumas informações serão coletadas
                automaticamente, uma vez que queremos garantir que você,
                usuário, acesse a plataforma UX GROUP de forma consistente e
                continue exatamente de onde parou. Ou seja, precisamos coletar,
                armazenar e acessar certas informações de identificação, e sem
                essas informações, a UX GROUP pode não funcionar corretamente.
                Sendo estas:<br></br>
                <span style={{ paddingLeft: "20px" }}>
                  <span style={{ fontWeight: "700" }}>1.</span> Informações de
                  geolocalização. Poderá coletar dados como a localização
                  precisa ou aproximada determinada a partir do seu endereço IP
                  ou GPS do dispositivo móvel. Também podemos coletar essas
                  informações quando você não estiver usando a plataforma se
                  você habilitar isso por meio de suas configurações ou
                  permissões de dispositivo
                </span>
                <br></br>
                <span style={{ paddingLeft: "20px" }}>
                  <span style={{ fontWeight: "700" }}>2.</span>Informações de
                  transação de pagamento. Como instrumento de pagamento usado,
                  data e hora, valor do pagamento, data de vencimento do
                  instrumento de pagamento e código postal de cobrança, endereço
                  de email, seu endereço e outros detalhes relacionados à
                  transações bancárias.
                </span>
              </span>
              <br></br>
              <br></br>

              <h3>3. DURANTE O USO DA PLATAFORMA</h3>
              <span style={{ paddingLeft: "10px" }}>
                <span style={{ fontWeight: "700" }}>1.</span> Na Plataforma,
                poderão ser utilizados cookies, sendo que o usuário pode, a
                qualquer instante, ativar em seu navegador mecanismos para
                informá-lo quando estiverem acionados ou até mesmo desativá-los.
              </span>
              <br></br>
              <span style={{ paddingLeft: "10px" }}>
                <span style={{ fontWeight: "700" }}>2.</span> Apesar disso, no
                caso da Plataforma, nenhuma dessas informações está associada ao
                usuário enquanto indivíduo. Tudo é mensurado somente de forma
                anônima e agregada. As informações que os cookies permitem
                rastrear referem-se à sua atividade de navegação, de modo que os
                cookies não capturam endereço individual de e-mail ou qualquer
                informação particular sobre o Usuário.
              </span>
              <br></br>
              <br></br>
              <h3>4. FINALIDADE DE USO DOS DADOS PESSOAIS </h3>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  1.
                </span>
                Os dados pessoais do Usuário serão utilizados, entre outras,
                para as seguintes finalidades, observadas as condições dos
                Termos e Condições e Regulamento da Plataforma:
              </span>
              <br></br>
              <span style={{ paddingLeft: "20px" }}>
                <span style={{ fontWeight: "700" }}>1.</span> Permitir que o
                Usuário se cadastre em campanhas;
              </span>
              <br></br>
              <span style={{ paddingLeft: "20px" }}>
                <span style={{ fontWeight: "700" }}>2.</span> Identificar o
                Usuário, aperfeiçoar a navegabilidade da Plataforma e
                personalizar sua experiência interativa durante a utilização da
                Plataforma;
              </span>
              <br></br>
              <span style={{ paddingLeft: "20px" }}>
                <span style={{ fontWeight: "700" }}>3.</span> PDesenvolver novos
                produtos, serviços e funcionalidades para os usuários;
              </span>
              <br></br>
              <span style={{ paddingLeft: "20px" }}>
                <span style={{ fontWeight: "700" }}>4.</span> Cumprir com
                obrigações legais de coleta e compartilhamento de dados com o
                poder público, na forma da legislação e regulamentação
                aplicáveis;
              </span>
              <br></br>
              <span style={{ paddingLeft: "20px" }}>
                <span style={{ fontWeight: "700" }}>5.</span> Permitir prevenção
                à fraude;
              </span>
              <br></br>
              <span style={{ paddingLeft: "20px" }}>
                <span style={{ fontWeight: "700" }}>6.</span> Permitir a
                divulgação de propaganda direcionada aos usuários e enviar
                e-mails promocionais, caso o usuário tenha optado por receber
                tais comunicações no momento do cadastro;
              </span>
              <br></br>
              <span style={{ paddingLeft: "20px" }}>
                <span style={{ fontWeight: "700" }}>7.</span> Solicitações para
                a participação do Usuário em pesquisas;
              </span>
              <br></br>
              <span style={{ paddingLeft: "20px" }}>
                <span style={{ fontWeight: "700" }}>8.</span> Responder a
                solicitações de natureza judicial e/ou administrativa;
              </span>
              <br></br>
              <span style={{ paddingLeft: "20px" }}>
                <span style={{ fontWeight: "700" }}>9.</span> Elaborar
                estatísticas gerais;
              </span>
              <br></br>
              <span style={{ paddingLeft: "20px" }}>
                <span style={{ fontWeight: "700" }}>10.</span> Responder às
                dúvidas e solicitações dos Usuários;
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  2.
                </span>
                Campanhas e Prestadores de Serviço. O Usuário entende e concorda
                que, caso se interesse em participar de uma das campanhas
                disponibilizadas na Plataforma,(conforme descrito na Cláusula
                2.3) serão compartilhados com nossos parceiros comerciais
                envolvidos na realização da campanha para fins de análise de
                perfil e envio de prêmios, caso aplicável, os seguintes dados
                pessoais do Usuário: [descrever]
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  3.
                </span>
                Para a execução dos recursos e funcionalidades disponibilizadas
                na Plataforma, a UX GROUP utiliza prestadores de serviço
                terceirizados, tais como gerenciamento e fornecimento de bancos
                de dados e hospedagem em nuvem. Os referidos terceiros possuem
                políticas de segurança adequadas e apropriadas.
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  4.
                </span>
                Caso o Usuário opte por receber comunicações contendo materiais
                promocionais acerca dos serviços prestados pela UX GROUP e das
                marcas de empresas parceiras, o Usuário poderá, a qualquer
                tempo, solicitar o descadastro de seu e-mail através de link
                disponibilizado em tais comunicações.
              </span>
              <br></br>
              <br></br>
              <h3>5. COMPARTILHAMENTO DE DADOS</h3>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  1.
                </span>
                Compartilhamento de dados. Sem prejuízo do demais disposto nesta
                Política, seus dados pessoais poderão ser compartilhados nas
                seguintes hipóteses: Seu contrato para compartilhar suas
                informações pessoais. Ao usar os serviços da UX GROUP suas
                informações poderão ser compartilhadas com terceiros, incluindo
                sites de redes sociais. Se você concordar em ter suas
                informações pessoais compartilhadas, suas informações pessoais
                poderão ser divulgadas a terceiros e as informações pessoais que
                você divulgar estarão sujeitas à política de privacidade e as
                práticas comerciais desse terceiro. Transferências Empresariais.
                Podemos compartilhar suas informações pessoais com outras
                entidades e afiliadas controladas pela UX GROUP, para fins
                comerciais e operacionais. À medida que continuamos a
                desenvolver nossos negócios, podemos vender ou comprar ativos.
                Se outra empresa comprar nossa empresa, negócio ou nossos
                ativos, ela também poderá adquirir as informações pessoais (e
                Informações de Uso) coletadas e armazenadas por nós, de forma
                que assumirá os direitos e obrigações referentes às suas
                informações pessoais, conforme descrito nesta Política de
                Privacidade. Além disso, se qualquer processo de falência ou
                recuperação for movido por ou contra nós, todas essas
                informações poderão ser consideradas um de nossos ativos e, como
                tal, poderão ser vendidas ou transferidas a terceiros.
                Divulgação Legal. Salvo determinação legal ou judicial, suas
                informações pessoais não serão transferidas a terceiros ou
                usadas para finalidades diferentes daquelas para as quais foram
                coletadas.
              </span>
              <br></br>
              <br></br>
              <h3>6. COMPARTILHAMENTO DE DADOS</h3>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  1.
                </span>
                Confidencialidade. A UX GROUP segue padrões rígidos de segurança
                e confidencialidade a fim de proteger as informações pessoais
                dos nossos usuários. Todas as informações pessoais fornecidas à
                UX GROUP serão coletadas por meios éticos e legais, de modo que
                os usuários serão informados sobre a finalidade da coleta de
                informação e por isso, caberá a ele optar por fornecer ou não a
                informação. A Empresa manterá íntegras as Informações Pessoais
                fornecidas pelos Usuários.
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  2.
                </span>
                Medida de segurança. Medidas padrão da indústria (por exemplo,
                firewalls e ferramentas de criptografia) para proteger contra a
                perda, uso indevido e alteração não autorizada de informações
                pessoais em nossa posse e controle.
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  3.
                </span>
                Cancelamento de cadastro. Caso o usuário queira cancelar seu
                cadastro, poderá entrar em contato conosco por meio de nossa
                CENTRAL DE ATENDIMENTO e fazer a solicitação. Seu pedido será
                processado num prazo de 15 (quinze) dias úteis. O Usuário também
                poderá entrar em contato conosco pelo mesmo canal de comunicação
                para fazer sugestões ou tirar dúvidas. CENTRAL DE ATENDIMENTO:
                marketing@uxgroup.com.br
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  4.
                </span>
                Responsabilidade. Esteja ciente de que, embora nos empenhamos em
                fornecer segurança para informações em nossa posse e controle,
                nenhum sistema de segurança pode prevenir contra possíveis
                brechas de segurança, e não nos responsabilizamos por usos ou
                divulgações de informações pessoais ou não-pessoais
                (anonimizadas) que surjam em conexão com o seu roubo.
              </span>
              <br></br>
              <br></br>
              <h3> 7. DIREITOS DOS USUÁRIOS E TRANSFERÊNCIA DE INFORMAÇÃO </h3>
              <span>
                O usuário poderá, a qualquer tempo, exercer os direitos
                previstos na Lei Geral de Proteção de Dados, entre eles:
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  1.
                </span>
                Confirmação da existência de tratamento de dados
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  2.
                </span>
                Acesso aos dados pessoais;
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  3.
                </span>
                Revogação do consentimento;
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  4.
                </span>
                Correção de dados pessoais incompletos, inexatos ou
                desatualizados;
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  5.
                </span>
                Eliminação dos dados pessoais tratados com o consentimento ou
                desnecessários, excessivos ou quando entender que algum ponto da
                LGPD não foi atendido;
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  6.
                </span>
                Informação sobre as hipóteses e com quais empresas, parceiros e
                outras instituições podemos compartilhar, ou receber dados
                pessoais referentes a você;
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  7.
                </span>
                Informação sobre a possibilidade de não fornecer consentimento e
                sobre as consequências da negativa, quando aplicável;
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  8.
                </span>
                Todas as solicitações serão tratadas de forma gratuita, e serão
                submetidas a uma prévia avaliação da sua identidade e da
                viabilidade do atendimento, a fim de cumprir com eventuais
                obrigações que impeçam o completo atendimento das requisições
                dos titulares de direito.
              </span>
              <br></br>
              <br></br>
              <h3>8. PERÍODO DE RETENÇÃO</h3>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  1.
                </span>
                Prazo de retenção dos dados. A UX GROUP reterá os dados pessoais
                pelo tempo necessário para cumprir a finalidade dos serviços e
                funcionalidades da Plataforma, para o cumprimento de uma
                obrigação legal, regulatória ou por ordem de uma autoridade ou
                no caso de interesse legítimo.
              </span>
              <br></br>
              <br></br>
              <h3>9. DISPOSIÇÕES GERAIS</h3>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  1.
                </span>
                Aplicabilidade. Se, por qualquer motivo, um tribunal competente
                considerar que qualquer disposição desta Política de Privacidade
                (ou qualquer parte da mesma) é inexequível, essa disposição (ou
                qualquer parte da mesma) será aplicada na medida do máximo
                permitido, de forma a refletir a intenção dos Termos da UX GROUP
                e as disposições restantes manter-se-ão em pleno vigor e efeito.
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "10px" }}>
                  2.
                </span>
                Tolerância. Qualquer tolerância a um descumprimento do presente
                será considerada mera liberalidade, não sendo considerada
                novação tampouco passando a integrar os presentes Termos.
              </span>
              <br></br>
              <span>
                <span style={{ fontWeight: "700", paddingLeft: "20px" }}>
                  1.
                </span>
                Foro. Fica eleito o foro de Barueri, SP, para dirimir eventuais
                conflitos advindos do presente instrumento, renunciando a
                qualquer outro, por mais privilegiado que seja.
              </span>

              <h2>Esta política é efetiva a partir de Agosto/2020</h2>
              <h2>UX GROUP.</h2>
            </div>
          </div>
        </div>
      </section>
      <Footer />
    </>
  );
}
